# 签名文件路径（相对于项目根目录）
storeFile=/data/data/com.termux/files/home/ZeroStudio/docs/zero_studio_signa.keystore
# 签名文件密码
storePassword=zero
# 密钥别名
keyAlias=zero
# 密钥密码
keyPassword=zero


# signature
# MY_RELEASE_STORE_FILE=/data/data/com.termux/files/home/ZeroStudio/docs/zero_studio_signa.keystore
# MY_RELEASE_STORE_PASSWORD=zero
# MY_RELEASE_KEY_ALIAS=zero
# MY_RELEASE_KEY_PASSWORD=zero