-keep class com.itsaky.androidide.app.IDEApplication { *; }
-keep class me.rerere.rikkahub.RikkaHubApp { *; }
-keep class com.termux.app.TermuxApplication { *; }
-keep class com.itsaky.androidide.app.BaseApplication { *; }
-keep class * extends android.app.Application { *; }
-keep class * extends androidx.multidex.MultiDexApplication { *; }
-keep class org.koin.** { *; }